# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 17 Mar 2018 21:39:14 +0000
*               @ALL          1
*               @user         8
