<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: mayuri
 * Date: Sun, 06 May 2018 12:18:11 +0200
 */

$conf['title'] = 'Humanitarian Blockchain Community';
$conf['template'] = 'bootstrap3';
$conf['sidebar'] = 'right';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['updatecheck'] = 0;
$conf['plugin']['googlemaps']['key'] = 'AIzaSyA0T2X1ZSkJeZ9D8HgzFI-qcj2FnnqwMyY';
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'cosmo';
$conf['tpl']['bootstrap3']['themeByNamespace'] = 1;
$conf['tpl']['bootstrap3']['fixedTopNavbar'] = 1;
$conf['tpl']['bootstrap3']['showHomePageLink'] = 1;
$conf['tpl']['bootstrap3']['individualTools'] = 1;
$conf['tpl']['bootstrap3']['navbarLabels'] = 'login,register,tools,page,expand';
$conf['tpl']['bootstrap3']['fluidContainerBtn'] = 1;
$conf['tpl']['bootstrap3']['showDiscussion'] = 1;
$conf['tpl']['bootstrap3']['useGoogleAnalytics'] = 1;
$conf['tpl']['bootstrap3']['showPageIcons'] = 1;

// end auto-generated content
