<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: mayuri
 * Date: Thu, 17 May 2018 23:40:03 +0200
 */

$conf['title'] = 'Humanitarian Blockchain Community';
$conf['sidebar'] = 'right';
$conf['license'] = 'cc-by-sa';
$conf['tocminheads'] = '2';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['updatecheck'] = 0;
$conf['plugin']['captcha']['mode'] = 'text';
$conf['plugin']['captcha']['loginprotect'] = 1;
$conf['plugin']['discussion']['automatic'] = 1;
$conf['plugin']['discussion']['allowguests'] = 0;
$conf['plugin']['discussion']['showguests'] = 0;
$conf['plugin']['discussion']['newestfirst'] = 1;
$conf['plugin']['discussion']['visibilityButton'] = 1;
$conf['plugin']['indexmenu']['aclcache'] = 'user';
$conf['plugin']['openlayersmap']['enableGoogle'] = 1;
$conf['plugin']['openlayersmap']['googleAPIkey'] = 'AIzaSyC08P9MUOH41OI0tna9AdZY5avVeyC6ALw';
$conf['plugin']['openlayersmap']['default_autozoom'] = 1;
$conf['plugin']['simplenavi']['sort'] = 'ascii';
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'cosmo';
$conf['tpl']['bootstrap3']['themeByNamespace'] = '1';
$conf['tpl']['bootstrap3']['fixedTopNavbar'] = '1';
$conf['tpl']['bootstrap3']['showHomePageLink'] = '1';
$conf['tpl']['bootstrap3']['individualTools'] = '1';
$conf['tpl']['bootstrap3']['navbarLabels'] = 'login,register,tools,page,expand';
$conf['tpl']['bootstrap3']['fluidContainerBtn'] = '1';
$conf['tpl']['bootstrap3']['showDiscussion'] = '1';
$conf['tpl']['bootstrap3']['useGoogleAnalytics'] = '1';
$conf['tpl']['bootstrap3']['showPageIcons'] = '1';
$conf['plugin']['googlemaps']['key'] = 'AIzaSyA0T2X1ZSkJeZ9D8HgzFI-qcj2FnnqwMyY';

// end auto-generated content
